### ISSUE TITLE
Example program issues

### ISSUE THREAD

**Issue by JimothyJohn** [lunarring/latentblending#17]
I've noticed that when running the samples anywhere but from the root of the repository they throw the error:

```bash
ModuleNotFoundError: No module named 'latentblending'
```

This occurs even after installing the latentblending package successfully, both via pip and setup.py. I'm guessing this is an environment issue, but to make it easier for beginners to deploy I'd recommend putting one of the Python programs in the examples/ directory into the root of the repo.

**Comment by jsd-lunar** [comment]
good point, thanks!
