### ISSUE TITLE
xformers not found

### ISSUE THREAD

**Issue by ipostr08** [lunarring/latentblending#6]
I've installed xformers using conda but I get "No module 'xformers'. Proceeding without it."
conda list
...
xformers                  0.0.16.dev432+git.bc08bbc py310_cu11.3_pyt1.12.1    xformers/label/dev

I've tried to install xformers using pip but that comes with its own issues (e.g. https://github.com/facebookresearch/xformers/issues/473).

**Comment by lunarring** [comment]
xformers can be quite fun to install.
What I found helpful is to clone the xformers github, install the dependencies and then run ```pip install -e .``` - which compiles xformers. Alternatively there are also pip wheels:
```pip install -q https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+4c06c79.d20221205-cp38-cp38-linux_x86_64.whl ```
good luck :)

**Comment by maxlund** [comment]
I would suggest building it yourself, never worked with pip for me. Then just copying/linking the xformers into your virtual env's library directory.
