### ISSUE TITLE
Example of upscaling with multi-transition

### ISSUE THREAD

**Issue by ipostr08** [lunarring/latentblending#8]
Not a bug but it would be useful to get an example of upscaling with multi-transition.

**Comment by lunarring** [comment]
sure! here it is.
https://github.com/lunarring/latentblending/blob/main/example4_upscaling.py

**Comment by ipostr08** [comment]
I only see the transition between two prompts and seeds in this example, not a call to run_multi_transition(). But I'll stop being lazy and actually look at the code and try to figure it out :)

**Comment by lunarring** [comment]
Ops -  missed the "multi".
The truth is I don't have a good workflow for that so far. Experimenting with different options.
The simplest is the following workflow
- make a transition from promptA -> promptB with seeds A and B
- upscale this one similar to example4, resulting in A->B movie file AtoB.mp4
- recycle promptB and seedB and make another transition to promptC and seedC
- upscale, resulting in B->C with movie file BtoC.mp4
- ... more with the same scheme...
- when done, concatenate the movies using the function concatenate_movies from movie_util.py:
concatenate_movies(fp_final=cocat.mp4, list_fp_movies=["AtoB.mp4", "BtoC.mp4",...])
hope this helps! working on a new gradio interface and workflow. will be online soonish.

**Comment by ipostr08** [comment]
Thanks! I got it mostly working yesterday, just have to fix an issue for longer movies (too many open files if I save all images). It looks really cool, great job with the project.
